apiVersion: v1
kind: Secret
metadata:
  name: spiritblade-secrets
type: Opaque
stringData:
  # MySQL
  mysql-root-password: "root"
  mysql-database: "spiritblade"
  
  # MinIO
  minio-access-key: "minioadmin"
  minio-secret-key: "minioadmin"
  
  # App
  jwt-secret: "my-super-secret-jwt-key-change-me-in-prod-1234567890"
  riot-api-key: "RGAPI-PLACEHOLDER"
  google-ai-api-key: "GOOGLE-AI-PLACEHOLDER"
  ssl-password: "changeit"
